### ISSUE TITLE
TypeError: platform.warn is not a function

### ISSUE THREAD

**Issue by arnthorsnaer** [bwp91/homebridge-ewelink-sonoff#11]
**What issue do you have?**
I have no devices set up with Ewelink yet, but was setting up the plugin in Homebridge. This might explain the error I'm getting.... if so it might be better handled. If not do you know what might be causing this?  (yes, I'm adding the devices tomorrow).

**Which version of the package are you using?**

homebridge-ewelink-sonoff v2.5.8
Node.js Version v12.18.3
Npm Version v6.14.6

**Please paste any relevant logs below**

```
[7/25/2020, 2:06:28 AM] [eWeLink] Initializing eWeLink platform...
[7/25/2020, 2:06:28 AM] [eWeLink] Plugin has finished initialising. Starting synchronisation with eWeLink account.
[7/25/2020, 2:06:31 AM] [eWeLink] ** eWeLink synchronisation error: **
[7/25/2020, 2:06:31 AM] [eWeLink] TypeError: platform.warn is not a function
    at eWeLink.removeAllAccessories (/usr/local/lib/node_modules/homebridge-ewelink-sonoff/lib/eWeLink.js:630:16)
    at /usr/local/lib/node_modules/homebridge-ewelink-sonoff/lib/eWeLink.js:59:31
    at /usr/local/lib/node_modules/homebridge-ewelink-sonoff/lib/eWeLink.js:112:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[7/25/2020, 2:06:31 AM] [eWeLink] ** Plugin will not be loaded. **
```

**Comment by bwp91** [comment]
Hey,
Thanks for highlighting this to me.
It was indeed an issue with installing the plugin with no devices, something I had overlooked.
Should be fixed in the version I just released - v2.5.9.
Let me know how you get on!

**Comment by arnthorsnaer** [comment]
Sure no problem, glad to help. It's working great with the changes in v.2.5.9. Now to add some devices.

**Comment by bwp91** [comment]
At least it’s not crashing Homebridge with no devices now.
But this plugin does indeed work better with devices rather than without. Have fun with your new toys!
