### ISSUE TITLE
cannot be refreshed due to missing type parameter.

### ISSUE THREAD

**Issue by kamaruszamanjufri** [bwp91/homebridge-ewelink-sonoff#13]
**What issue do you have?**
...
cannot be refreshed due to missing type parameter.
**Which version of the package are you using?**
...
2.9.0
**Please paste any relevant logs below**
...
[7/27/2020, 9:51:33 AM] [eWeLink] [Hall Fan 2] will not be refreshed as it has been reported offline.
[7/27/2020, 9:51:33 AM] [eWeLink] [Hall Fan 2] has been reported [online].
[7/27/2020, 9:51:33 AM] [eWeLink] [Hall Fan 2] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).
[7/27/2020, 9:51:34 AM] [eWeLink] [Hall Fan 2] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).
[7/27/2020, 9:51:40 AM] [eWeLink] [Hall Fan 2] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).
[7/27/2020, 9:51:41 AM] [eWeLink] [Hall Fan 2] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).
[7/27/2020, 9:51:41 AM] [eWeLink] [Hall Fan 2] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).

[7/27/2020, 9:51:46 AM] [eWeLink] [Hall Fan1] has been reported [online].
[7/27/2020, 9:51:53 AM] [eWeLink] [Hall Fan1] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).
[7/27/2020, 9:51:53 AM] [eWeLink] [Hall Fan1] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).
[7/27/2020, 9:51:54 AM] [eWeLink] [Hall Fan1] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).

[7/27/2020, 9:54:02 AM] [eWeLink] [Water Pump] will not be refreshed as it has been reported offline.
[7/27/2020, 9:54:02 AM] [eWeLink] [Water Pump] has been reported [online].
[7/27/2020, 9:54:02 AM] [eWeLink] [Water Pump] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).
[7/27/2020, 9:54:24 AM] [eWeLink] [Water Pump] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).
[7/27/2020, 9:54:26 AM] [eWeLink] [Water Pump] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.).

**Comment by bwp91** [comment]
Hiya,

Please could you do two things for me:

- Turn on debug logging in the plugin "optional" settings part
- Update to v9.2.1

Then restart Homebridge and send me new logs.

Please note this update won't fix your issue, but it will give me more insight into why you are getting this error.

Thanks
Ben

**Comment by kamaruszamanjufri** [comment]
New logs;

[7/27/2020, 3:45:53 PM] [eWeLink] [Hall Fan1] updating [light] to [true].
[7/27/2020, 3:45:53 PM] [eWeLink] Web socket message sent. This text is yellow for clarity.
{
  "apikey": "**hidden**",
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ]
  },
  "action": "update",
  "sequence": 1595835953576,
  "userAgent": "app"
}
[7/27/2020, 3:45:53 PM] [eWeLink] LAN message received.
{
  "action": "update",
  "deviceid": "**hidden**",
  "params": {
    "light": "on",
    "fan": "on",
    "speed": 1,
    "startup_light": "on",
    "startup_fan": "off"
  }
}
[7/27/2020, 3:45:53 PM] [eWeLink] [Hall Fan1] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 3:45:53 PM] [eWeLink] [Hall Fan1] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.). Debugging: [refresh:fan:4]
[7/27/2020, 3:45:54 PM] [eWeLink] LAN message received.
{
  "action": "update",
  "deviceid": "**hidden**",
  "params": {
    "light": "on",
    "fan": "on",
    "speed": 1,
    "startup_light": "on",
    "startup_fan": "off"
  }
}
[7/27/2020, 3:45:54 PM] [eWeLink] [Hall Fan1] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 3:45:54 PM] [eWeLink] [Hall Fan1] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.). Debugging: [refresh:fan:4]
[7/27/2020, 3:45:54 PM] [eWeLink] LAN message received.
{
  "action": "update",
  "deviceid": "**hidden**",
  "params": {
    "light": "on",
    "fan": "on",
    "speed": 1,
    "startup_light": "on",
    "startup_fan": "off"
  }
}
[7/27/2020, 3:45:54 PM] [eWeLink] [Hall Fan1] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 3:45:54 PM] [eWeLink] [Hall Fan1] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.). Debugging: [refresh:fan:4]
[7/27/2020, 3:45:55 PM] [eWeLink] LAN message received.
{
  "action": "update",
  "deviceid": "**hidden**",
  "params": {
    "light": "on",
    "fan": "on",
    "speed": 1,
    "startup_light": "on",
    "startup_fan": "off"
  }
}
[7/27/2020, 3:45:55 PM] [eWeLink] [Hall Fan1] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 3:45:55 PM] [eWeLink] [Hall Fan1] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.). Debugging: [refresh:fan:4]


[7/27/2020, 3:47:14 PM] [eWeLink] [Hall Fan 2] updating [light] to [true].
[7/27/2020, 3:47:14 PM] [eWeLink] Web socket message sent. This text is yellow for clarity.
{
  "apikey": "**hidden**",
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "on",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ]
  },
  "action": "update",
  "sequence": 1595836034286,
  "userAgent": "app"
}
[7/27/2020, 3:47:14 PM] [eWeLink] LAN message received.
{
  "action": "update",
  "deviceid": "**hidden**",
  "params": {
    "light": "on",
    "fan": "on",
    "speed": 2,
    "startup_light": "on",
    "startup_fan": "off"
  }
}
[7/27/2020, 3:47:14 PM] [eWeLink] [Hall Fan 2] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 3:47:14 PM] [eWeLink] [Hall Fan 2] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.). Debugging: [refresh:fan:4]
[7/27/2020, 3:47:14 PM] [eWeLink] LAN message received.
{
  "action": "update",
  "deviceid": "**hidden**",
  "params": {
    "light": "on",
    "fan": "on",
    "speed": 2,
    "startup_light": "on",
    "startup_fan": "off"
  }
}
[7/27/2020, 3:47:14 PM] [eWeLink] [Hall Fan 2] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 3:47:14 PM] [eWeLink] [Hall Fan 2] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.). Debugging: [refresh:fan:4]
[7/27/2020, 3:47:15 PM] [eWeLink] LAN message received.
{
  "action": "update",
  "deviceid": "**hidden**",
  "params": {
    "light": "on",
    "fan": "on",
    "speed": 2,
    "startup_light": "on",
    "startup_fan": "off"
  }
}
[7/27/2020, 3:47:15 PM] [eWeLink] [Hall Fan 2] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 3:47:15 PM] [eWeLink] [Hall Fan 2] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.). Debugging: [refresh:fan:4]
[7/27/2020, 3:47:15 PM] [eWeLink] LAN message received.
{
  "action": "update",
  "deviceid": "**hidden**",
  "params": {
    "light": "on",
    "fan": "on",
    "speed": 2,
    "startup_light": "on",
    "startup_fan": "off"
  }
}
[7/27/2020, 3:47:15 PM] [eWeLink] [Hall Fan 2] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 3:47:15 PM] [eWeLink] [Hall Fan 2] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.). Debugging: [refresh:fan:4]

**Comment by bwp91** [comment]
I see.
You have a fan device which I haven't been able to implement into the plugin yet as I haven't found anyone with the device (until now!).
You can see in the [wiki](https://github.com/bwp91/homebridge-ewelink-sonoff/wiki/Supported-Devices) that fans are a work in progress.
If you have the time would you be happy to help me out? I'll leave my email address in the next comment

**Comment by bwp91** [comment]
bwp91@icloud.com

**Comment by bwp91** [comment]
Please try v2.9.2 to see if this has been fixed

**Comment by kamaruszamanjufri** [comment]
> [bwp91@icloud.com](mailto:bwp91@icloud.com)
Sure.


> Please try v2.9.2 to see if this has been fixed
Odd things happened.

When I turn on the light, the fan will turn off.

[7/27/2020, 4:46:06 PM] [eWeLink] [Hall Fan 2] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 4:46:09 PM] [eWeLink] [Hall Fan 2] updating [light] to [false].
[7/27/2020, 4:46:09 PM] [eWeLink] Web socket message sent. This text is yellow for clarity.
{
  "apikey": "**hidden**",
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "off",
        "outlet": 0
      },
      {
        "switch": "off",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ]
  },
  "action": "update",
  "sequence": 1595839569400,
  "userAgent": "app"
}
[7/27/2020, 4:46:09 PM] [eWeLink] LAN message received.
{
  "source": "lan",
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "light": "off",
    "fan": "off",
    "speed": 1
  }
}
[7/27/2020, 4:46:09 PM] [eWeLink] [Hall Fan 2] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 4:46:09 PM] [eWeLink] LAN message received.
{
  "source": "lan",
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "light": "off",
    "fan": "off",
    "speed": 1
  }
}
[7/27/2020, 4:46:09 PM] [eWeLink] [Hall Fan 2] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 4:46:10 PM] [eWeLink] LAN message received.
{
  "source": "lan",
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "light": "off",
    "fan": "off",
    "speed": 1
  }
}
[7/27/2020, 4:46:10 PM] [eWeLink] [Hall Fan 2] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 4:46:10 PM] [eWeLink] LAN message received.
{
  "source": "lan",
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "light": "off",
    "fan": "off",
    "speed": 1
  }
}
[7/27/2020, 4:46:10 PM] [eWeLink] [Hall Fan 2] was externally updated (see above WS/LAN message) and will be refreshed.

**Comment by bwp91** [comment]
Okay i'm going to need more in depth info about how the fan works. Drop me an email and we can get this working. 
I've been wanting to implement the fan for a long time now!

**Comment by kamaruszamanjufri** [comment]
> Okay i'm going to need more in depth info about how the fan works. Drop me an email and we can get this working.
> I've been wanting to implement the fan for a long time now!

Ok. Already email to you.

**Comment by bwp91** [comment]
> Ok. Already email to you.
I sent you a reply about 30 mins ago :)

**Comment by bwp91** [comment]
I also just noticed a bug in the code, please try 2.9.3 too.

**Comment by kamaruszamanjufri** [comment]
Ok. Already reply your email.

**Comment by kamaruszamanjufri** [comment]
> I also just noticed a bug in the code, please try 2.9.3 too.

Done. But still got issues. 
1. Turn on the light, will turn on the fan also
2. Turn off the light, the fan will go to the minimum speed.

**Comment by bwp91** [comment]
i appreciate your patience! please try 2.9.4

**Comment by kamaruszamanjufri** [comment]
It works.
For the fan, when it is turn on, the speed will be maximum.

**Comment by bwp91** [comment]
> For the fan, when it is turn on, the speed will be maximum.
Is this what happens? Or what you would like to happen?
Would it be better to be on a low speed if turned on?

**Comment by kamaruszamanjufri** [comment]
> Is this what happens? Or what you would like to happen?
Yes.

> Would it be better to be on a low speed if turned on?
I believe so for me.

**Comment by kamaruszamanjufri** [comment]
Similar error "cannot be refreshed due to missing type parameter" but for the different device.

[7/27/2020, 9:36:08 PM] [eWeLink] [Ventilation Hall 1] has been reported [online].
[7/27/2020, 9:36:08 PM] [eWeLink] [1000644f2f] WS message has nothing useful for Homebridge.
[7/27/2020, 9:36:08 PM] [eWeLink] WS message received.
{
  "source": "ws",
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "init": 1,
    "alarmType": "pcv",
    "alarmVValue": [
      -1,
      -1
    ],
    "alarmCValue": [
      -1,
      -1
    ],
    "alarmPValue": [
      -1,
      -1
    ],
    "switch": "on",
    "voltage": "231.13",
    "current": "0.19",
    "oneKwh": "stop"
  }
}
[7/27/2020, 9:36:08 PM] [eWeLink] [Ventilation Hall 1] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 9:36:08 PM] [eWeLink] LAN message received.
{
  "source": "lan",
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "alarmVValue": [
      -1,
      -1
    ],
    "alarmCValue": [
      -1,
      -1
    ],
    "alarmPValue": [
      -1,
      -1
    ],
    "switch": "on",
    "voltage": 231.13,
    "current": 0.19
  }
}
[7/27/2020, 9:36:08 PM] [eWeLink] [Ventilation Hall 1] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 9:36:08 PM] [eWeLink] WS message received.
{
  "source": "ws",
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "voltage": "231.13",
    "current": "0.19"
  }
}
[7/27/2020, 9:36:08 PM] [eWeLink] [Ventilation Hall 1] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 9:36:08 PM] [eWeLink] [Ventilation Hall 1] cannot be refreshed due to missing type parameter. Please remove accessory from the Homebridge cache along with any secondary devices (SW1, SW2, etc.). Debugging: [refresh:outlet:1]
[7/27/2020, 9:36:09 PM] [eWeLink] LAN message received.
{
  "source": "lan",
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "alarmVValue": [
      -1,
      -1
    ],
    "alarmCValue": [
      -1,
      -1
    ],
    "alarmPValue": [
      -1,
      -1
    ],
    "switch": "on",
    "voltage": 231.13,
    "current": 0.19
  }
}
[7/27/2020, 9:36:09 PM] [eWeLink] [Ventilation Hall 1] was externally updated (see above WS/LAN message) and will be refreshed.
[7/27/2020, 9:36:09 PM] [eWeLink] LAN message received.
{
  "source": "lan",
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "alarmVValue": [
      -1,
      -1
    ],
    "alarmCValue": [
      -1,
      -1
    ],
    "alarmPValue": [
      -1,
      -1
    ],
    "switch": "on",
    "voltage": 231.13,
    "current": 0.19
  }
}

**Comment by bwp91** [comment]
With regards to the fan, have you received my second email?

With regards to the outlet, even though there is an error message, there is actually nothing going wrong. I'll hide the error in the next release.

Thanks
Ben

**Comment by kamaruszamanjufri** [comment]
Hi,

With regards to the fan, have you received my second email?

-Yes. Already replied.

With regards to the outlet, even though there is an error message, there is actually nothing going wrong. I'll hide the error in the next release.

-Noted.



For the Home App status, it still didn’t update correctly for no responses devices.
Regards,
kamaruszaman jufri
019-3803558
kamarus@gmail.com

**Comment by bwp91** [comment]
I realise there is still a slight issue with the initial fan speed when you turn the fan on. It is something I am working on.
For now I will keep this issue open until I am happy it works consistently between different apps ie Home App, Eve App, etc.

**Comment by kamaruszamanjufri** [comment]
Noted

**Comment by kamaruszamanjufri** [comment]
New error prompt out with the new update.

online/offline status could not be updated - [TypeError: Cannot read property 'eweApiKey' of undefined
    at eWeLinkWS.requestUpdate (/homebridge/node_modules/homebridge-ewelink-sonoff/lib/eWeLinkWS.js:225:36)
    at eWeLink.receiveDeviceUpdate (/homebridge/node_modules/homebridge-ewelink-sonoff/lib/eWeLink.js:648:36)
    at EventEmitter.<anonymous> (/homebridge/node_modules/homebridge-ewelink-sonoff/lib/eWeLink.js:115:27)
    at EventEmitter.emit (events.js:310:20)
    at WebSocket.<anonymous> (/homebridge/node_modules/homebridge-ewelink-sonoff/lib/eWeLinkWS.js:114:29)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (/homebridge/node_modules/homebridge-ewelink-sonoff/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:310:20)
    at Receiver.dataMessage (/homebridge/node_modules/homebridge-ewelink-sonoff/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/homebridge/node_modules/homebridge-ewelink-sonoff/node_modules/ws/lib/receiver.js:367:17)].

**Comment by bwp91** [comment]
Hi,
This should be fixed in v2.15.2.
Thanks!

**Comment by bwp91** [comment]
> I realise there is still a slight issue with the initial fan speed when you turn the fan on. It is something I am working on.
> 
> For now I will keep this issue open until I am happy it works consistently between different apps ie Home App, Eve App, etc.

Just an update though no progress.
I really want to sort the fan out but as I don't own the device i need someone to help me.
So it's like a paused work in progress.

**Comment by kamaruszamanjufri** [comment]
sure. anything I can help.

**Comment by dipen26** [comment]
Can you help me with configuration? I been trying to add Fan but always fails, and says missing Parameter. Please help me in adding para. Thank you

**Comment by bwp91** [comment]
> Can you help me with configuration? I been trying to add Fan but always fails, and says missing Parameter. Please help me in adding para. Thank you

Which fan device do you have?
Please try removing it from the Homebridge cache and then restarting Homebridge. Let me know if this works.
Thanks

**Comment by dipen26** [comment]
I have IFAN 3 by son off.

**Comment by bwp91** [comment]
The iFan03 should be automatically added as a fan, there is no "extra configuration" needed for this device.
Please try removing it from the Homebridge cache and then restarting Homebridge. Let me know if this works.
