### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by wtfloris** [bwp91/homebridge-ewelink-sonoff#17]
Hi everyone,

I've just installed this plugin, and I'm getting a very long error that seems to boil down to some expired certificate. Is this something on ewelink's side or is this something I'm doing wrong?

I've posted logs below. `debug` and `debugReqRes` are turned on.

Cheers

```
Aug  3 20:19:24 pi_unit_0 homebridge[22779]: [2020-8-3 20:19:24] [eWeLink] Plugin has finished initialising. Starting synchronisation with eWeLink account.
Aug  3 20:19:24 pi_unit_0 homebridge[22779]: [2020-8-3 20:19:24] [eWeLink] HTTP API host received [eu-api.coolkit.cc:8080].
Aug  3 20:19:24 pi_unit_0 homebridge[22779]: [2020-8-3 20:19:24] [eWeLink] Sending HTTP login request. This text is yellow for clarity.
Aug  3 20:19:24 pi_unit_0 homebridge[22779]: {
Aug  3 20:19:24 pi_unit_0 homebridge[22779]:   "appid": "oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq",
Aug  3 20:19:24 pi_unit_0 homebridge[22779]:   "nonce": 159647876466700,
Aug  3 20:19:24 pi_unit_0 homebridge[22779]:   "password": "**hidden**",
Aug  3 20:19:24 pi_unit_0 homebridge[22779]:   "ts": 1596478764,
Aug  3 20:19:24 pi_unit_0 homebridge[22779]:   "version": 8,
Aug  3 20:19:24 pi_unit_0 homebridge[22779]:   "email": "**hidden**"
Aug  3 20:19:24 pi_unit_0 homebridge[22779]: }
Aug  3 20:19:26 pi_unit_0 homebridge[22779]: [2020-8-3 20:19:26] [eWeLink] ** eWeLink synchronisation error: **
Aug  3 20:19:26 pi_unit_0 homebridge[22779]: [2020-8-3 20:19:26] [eWeLink] { Error: certificate has expired
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:     at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:     at emitNone (events.js:106:13)
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:     at TLSSocket.emit (events.js:208:7)
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:     at TLSSocket._finishInit (_tls_wrap.js:643:8)
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:   code: 'CERT_HAS_EXPIRED',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:   config:
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:    { url: 'https://eu-disp.coolkit.cc:8080/dispatch/app',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      method: 'post',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      data: '{"appid":"oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq","nonce":159647876622400,"ts":1596478766,"version":8}',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      headers:
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:       { Accept: 'application/json, text/plain, */*',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         'Content-Type': 'application/json;charset=UTF-8',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         Authorization: 'Bearer 8342307fd086eb2862f87fc36d471c50c42897ff',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         'User-Agent': 'axios/0.19.2',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         'Content-Length': 96 },
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      transformRequest: [ [Function: transformRequest] ],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      transformResponse: [ [Function: transformResponse] ],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      timeout: 0,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      adapter: [Function: httpAdapter],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      xsrfCookieName: 'XSRF-TOKEN',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      xsrfHeaderName: 'X-XSRF-TOKEN',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      maxContentLength: -1,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      validateStatus: [Function: validateStatus] },
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:   request:
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:    Writable {
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _writableState:
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:       WritableState {
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         objectMode: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         highWaterMark: 16384,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         finalCalled: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         needDrain: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         ending: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         ended: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         finished: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         destroyed: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         decodeStrings: true,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         defaultEncoding: 'utf8',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         length: 0,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         writing: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         corked: 0,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         sync: true,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         bufferProcessing: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         onwrite: [Function: bound onwrite],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         writecb: null,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         writelen: 0,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         bufferedRequest: null,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         lastBufferedRequest: null,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         pendingcb: 0,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         prefinished: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         errorEmitted: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         bufferedRequestCount: 0,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         corkedRequestsFree: [Object] },
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      writable: true,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      domain: null,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _events:
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:       { response: [Function: handleResponse],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         error: [Function: handleRequestError] },
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _eventsCount: 2,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _maxListeners: undefined,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _options:
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:       { protocol: 'https:',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         maxRedirects: 21,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         maxBodyLength: 10485760,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         path: '/dispatch/app',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         method: 'POST',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         headers: [Object],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         agent: undefined,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         agents: [Object],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         auth: undefined,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         hostname: 'eu-disp.coolkit.cc',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         port: '8080',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         nativeProtocols: [Object],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         pathname: '/dispatch/app' },
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _redirectCount: 0,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _redirects: [],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _requestBodyLength: 96,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _requestBodyBuffers: [ [Object] ],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _onNativeResponse: [Function],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _currentRequest:
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:       ClientRequest {
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         domain: null,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _events: [Object],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _eventsCount: 6,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _maxListeners: undefined,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         output: [],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         outputEncodings: [],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         outputCallbacks: [],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         outputSize: 0,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         writable: true,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _last: true,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         upgrading: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         chunkedEncoding: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         shouldKeepAlive: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         useChunkedEncodingByDefault: true,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         sendDate: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _removedConnection: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _removedContLen: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _removedTE: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _contentLength: null,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _hasBody: true,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _trailer: '',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         finished: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _headerSent: true,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         socket: [Object],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         connection: [Object],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _header: 'POST /dispatch/app HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=UTF-8\r\nAuthorization: Bearer 8342307fd086eb2862f87fc36d471c50c42897ff\r\nUser-Agent: axios/0.19.2\r\nContent-Length: 96\r\nHost: eu-disp.coolkit.cc:8080\r\nConnection: close\r\n\r\n',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _onPendingData: [Function: noopPendingOutput],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         agent: [Object],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         socketPath: undefined,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         timeout: undefined,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         method: 'POST',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         path: '/dispatch/app',
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _ended: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         res: null,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         aborted: undefined,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         timeoutCb: null,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         upgradeOrConnect: false,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         parser: null,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         maxHeadersCount: null,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         _redirectable: [Circular],
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:         [Symbol(outHeadersKey)]: [Object] },
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:      _currentUrl: 'https://eu-disp.coolkit.cc:8080/dispatch/app' },
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:   response: undefined,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:   isAxiosError: true,
Aug  3 20:19:26 pi_unit_0 homebridge[22779]:   toJSON: [Function] }
Aug  3 20:19:26 pi_unit_0 homebridge[22779]: [2020-8-3 20:19:26] [eWeLink] ** Plugin will not be loaded. **
```

**Comment by wtfloris** [comment]
I'm an idiot, my trusted certificates db is just out of date.

**Comment by wtfloris** [comment]
I shouldn't be so quick to discount stuff like this. Looks like everything outside homebridge/this plugin is handling HTTPS to this server just fine.

What could this be?

**Comment by bwp91** [comment]
Hi,
Out of interest which version of node are you on?

**Comment by wtfloris** [comment]
v8.17.0

I have zero experience with node, is that old?

**Comment by bwp91** [comment]
Any luck? 😀

**Comment by wtfloris** [comment]
Yeah got it working, but not without destroying the entire homebridge instance first :)

Thanks for the suggestion!
